import { Activity, Bot, ChevronDown, DatabaseZap, FlaskConical, RefreshCw, ShieldCheck, Shuffle, X } from 'lucide-react'
import { useState } from 'react'
import { Field } from './ProductForm'
import { GENERIC_VIDEO_PROFILE, VIDEO_MODEL_PROFILES, getVideoModelProfile, normalizeVideoSelection } from '../../shared/video-models.mjs'

const presets = {
  openai: { baseUrl: 'https://api.openai.com/v1', imageProtocol: 'openai', videoProtocol: 'openai', modelsPath: '/models', imagePath: '/images/edits\n/images/generations', imageStatusPath: '/media/status?task_id={id}', videoPath: '/videos', videoStatusPath: '/videos/{id}', videoContentPath: '/videos/{id}/content', authMode: 'bearer' },
  compatible: { baseUrl: '', imageProtocol: 'auto', videoProtocol: 'auto', modelsPath: '/models\n/v1/models', imagePath: '/media/generate\n/v1/media/generate\n/images/generations\n/v1/images/generations\n/responses', imageStatusPath: '/media/status?task_id={id}\n/v1/media/status?task_id={id}\n/skills/task-status?task_id={id}\n/v1/skills/task-status?task_id={id}\n/tasks/{id}', videoPath: '/media/generate\n/v1/media/generate\n/videos\n/videos/generations\n/v1/videos\n/v1/videos/generations', videoStatusPath: '/media/status?task_id={id}\n/v1/media/status?task_id={id}\n/skills/task-status?task_id={id}\n/v1/skills/task-status?task_id={id}\n/videos/{id}\n/videos/generations/{id}\n/tasks/{id}\n/v1/videos/{id}', videoContentPath: '/videos/{id}/content\n/v1/videos/{id}/content', authMode: 'bearer' },
}

const PathField = ({ label, value, onChange, disabled, placeholder }) => <Field label={label}><textarea className="api-paths" disabled={disabled} value={value || ''} onChange={(event) => onChange(event.target.value)} placeholder={placeholder}/></Field>
const Select = ({ value, onChange, disabled, children }) => <div className="select-wrap"><select value={value} onChange={(event) => onChange(event.target.value)} disabled={disabled}>{children}</select><ChevronDown size={14}/></div>
const firstModel = (value) => String(value || '').split(/[\n,，]/).map((item) => item.trim()).find(Boolean) || ''

function VideoSettings({ config, setConfig, disabled }) {
  const model = firstModel(config.videoModels || config.videoModel)
  const detectedProfile = getVideoModelProfile(model)
  const selectedProfile = config.videoProfile || (VIDEO_MODEL_PROFILES.includes(detectedProfile) ? detectedProfile.id : GENERIC_VIDEO_PROFILE.id)
  const profile = selectedProfile === 'custom' ? GENERIC_VIDEO_PROFILE : VIDEO_MODEL_PROFILES.find((item) => item.id === selectedProfile) || detectedProfile
  const custom = selectedProfile === 'custom'
  const selection = normalizeVideoSelection(profile, { duration: config.videoDuration, resolution: config.videoResolution, aspectRatio: config.videoAspectRatio, mode: config.videoMode })
  const update = (patch) => setConfig((current) => ({ ...current, ...patch }))
  function selectType(id) {
    const nextProfile = id === 'custom' ? GENERIC_VIDEO_PROFILE : VIDEO_MODEL_PROFILES.find((item) => item.id === id)
    const next = normalizeVideoSelection(nextProfile, {})
    const nextModel = nextProfile.id === 'custom' ? (VIDEO_MODEL_PROFILES.some((item) => item.id === model) ? '' : model) : nextProfile.id
    update({ videoProfile: nextProfile.id, videoModel: nextModel, videoModels: nextModel, videoDuration: next.duration, videoResolution: next.resolution, videoAspectRatio: next.aspectRatio, videoMode: next.mode, videoReferencePolicy: nextProfile.requiresImage ? 'require-public' : 'auto-t2v' })
  }
  return <section className="video-config"><div className="video-config-head"><div><strong>视频模型与输出规格</strong><small>所有选项都可手动选择；预设会自动限制模型实际支持的组合</small></div><span>{selection.duration === 'auto' ? '自动时长' : `${selection.duration} 秒`} · {selection.resolution} · {selection.aspectRatio}{selection.mode ? ` · ${selection.mode}` : ''}</span></div><div className="video-settings"><Field label="① 视频模型种类"><Select disabled={disabled} value={selectedProfile} onChange={selectType}>{VIDEO_MODEL_PROFILES.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}<option value="custom">自定义视频模型</option></Select></Field>
    <Field label="② 模型 ID / 模型池"><input disabled={disabled} value={config.videoModels || config.videoModel || ''} onChange={(event) => update({ videoModels: event.target.value, videoModel: firstModel(event.target.value) })} placeholder={custom ? '例如：my-video-model-v2' : '可替换为中转站实际模型 ID'}/></Field>
    <Field label="无公网参考图时"><Select disabled={disabled} value={config.videoReferencePolicy || 'auto-t2v'} onChange={(value) => update({ videoReferencePolicy: value })}><option value="auto-t2v">自动切换可用文生视频模型</option><option value="text-only" disabled={profile.requiresImage}>始终使用文生视频，不发送图片</option><option value="require-public">强制图生视频，必须公网 URL</option></Select></Field>
    <Field label="公开视频参考图 URL（可选）"><input disabled={disabled} value={config.videoReferenceUrl || ''} onChange={(event) => update({ videoReferenceUrl: event.target.value })} placeholder="媒体接口要求 URL 时填写 COS/CDN 图片地址"/></Field>
    <Field label="③ 视频时间长度">{custom ? <input disabled={disabled} value={selection.duration} onChange={(event) => update({ videoDuration: event.target.value })} placeholder="例如 5、10、15 或 auto"/> : <Select disabled={disabled} value={selection.duration} onChange={(value) => update({ videoDuration: value })}>{profile.durations.map((item) => <option value={item} key={item}>{item === 'auto' ? '自动' : `${item} 秒`}</option>)}</Select>}</Field>
    <Field label="④ 输出分辨率 / 大小">{custom ? <input disabled={disabled} value={selection.resolution} onChange={(event) => update({ videoResolution: event.target.value })} placeholder="例如 1080p 或 1080x1920"/> : <Select disabled={disabled} value={selection.resolution} onChange={(value) => { const forceStandard = /(?:kwvideo|seedance|jimeng)/i.test(profile.id) && ['1080p','4K'].includes(value); update({ videoResolution: value, ...(forceStandard ? { videoMode: '标准' } : {}) }) }}>{profile.resolutions.map((item) => <option value={item} key={item}>{item}</option>)}</Select>}</Field>
    <Field label="⑤ 画面尺寸 / 宽高比">{custom ? <input disabled={disabled} value={selection.aspectRatio} onChange={(event) => update({ videoAspectRatio: event.target.value })} placeholder="例如 9:16、16:9、1:1"/> : <Select disabled={disabled} value={selection.aspectRatio} onChange={(value) => update({ videoAspectRatio: value })}>{profile.ratios.map((item) => <option value={item} key={item}>{item}</option>)}</Select>}</Field>
    {custom ? <Field label="⑥ 质量 / 版本（可选）"><input disabled={disabled} value={selection.mode} onChange={(event) => update({ videoMode: event.target.value })} placeholder="例如 pro、standard、fast"/></Field> : profile.modes?.length ? <Field label="⑥ 质量 / 版本"><Select disabled={disabled} value={selection.mode} onChange={(value) => update({ videoMode: value })}>{profile.modes.map((item) => <option value={item} key={item}>{item}</option>)}</Select></Field> : <div className="video-profile-note">当前模型没有额外质量版本选项</div>}
    <Field label="⑦ 声音"><Select disabled={disabled || profile.audio === false} value={config.videoAudio === false ? 'false' : 'true'} onChange={(value) => update({ videoAudio: value === 'true' })}><option value="true">生成语音与环境音</option><option value="false">静音视频</option></Select></Field>
  </div><p className="video-profile-help">{profile.requiresImage ? '此模型仅支持图生视频：必须提供一张公网首帧图；系统会把单个 URL 写入 params.images。' : custom ? '自定义模式会按原值把 duration、resolution、aspect_ratio 和 mode 传给兼容接口。' : `${profile.label}：时长、分辨率和尺寸已按模型能力联动，切换模型会自动恢复该模型的安全默认值。`} {profile.audio === false ? '该接口文档没有声明音频开关，不能保证生成声音；需要声音请选带“有声”标记的模型。' : '已启用声音时会按模型要求提交 audio=true。'} 回调地址始终作为 notify_url 顶层字段提交；自动模式下，本地图片无法直传时会记录并执行所选回退策略。</p></section>
}

export function ApiModal({ config, setConfig, agents, refreshAgents, close, testApi, testing, loadModels, loadingModels }) {
  const [advanced, setAdvanced] = useState(false)
  const update = (key, value) => setConfig((current) => ({ ...current, [key]: value }))
  function selectProvider(provider) { setConfig((current) => ({ ...current, provider, ...presets[provider], apiKey: current.apiKey })) }
  const selectedProvider = config.provider === 'openai' ? 'openai' : 'compatible'
  const disabled = config.demoMode
  const agent = agents?.[config.agentProvider]
  return <div className="modal-backdrop" role="presentation"><div className="modal api-modal" role="dialog" aria-modal="true" aria-label="智能体与 API"><div className="modal-head"><div><strong>智能体与媒体 API</strong><small>Codex / Claude 使用现有登录额度处理文本；媒体接口只负责图片与视频</small></div><button aria-label="关闭 API 接入" onClick={close}><X/></button></div>
    <label className="mode-switch"><input type="checkbox" checked={config.demoMode} onChange={(event) => update('demoMode', event.target.checked)}/><span><FlaskConical size={17}/><b>本地演示模式</b><small>无需 API Key，完整模拟六阶段工作流</small></span></label>
    <div className={`live-config ${disabled ? 'disabled' : ''}`} aria-disabled={disabled}><div className="agent-connect"><Bot size={18}/><div><strong>本地智能体</strong><small>安装器已部署 ugc-flow-agent 和商家 UGC Skills</small></div><span className={agent?.authenticated ? 'connected' : ''}>{agent?.authenticated ? '已连接' : agent?.installed ? '未登录' : agents ? '未安装' : '检测中'}</span><button onClick={refreshAgents} disabled={disabled}><RefreshCw size={13}/>重新检测</button></div><div className="modal-grid">
      <Field label="文本与 Skill 智能体"><Select disabled={disabled} value={config.agentProvider || 'codex'} onChange={(value) => setConfig((current) => ({ ...current, agentProvider: value, imageSource: value === 'codex' ? 'agent' : 'api', ...(value === 'claude' ? { imageProtocol: 'media' } : {}) }))}><option value="codex">Codex（使用 ChatGPT/Codex 额度）</option><option value="claude">Claude Code（使用 Claude 额度）</option></Select></Field>
      <Field label="图片来源"><Select disabled={disabled} value={config.imageSource || 'api'} onChange={(value) => update('imageSource', value)}><option value="agent">Codex 生图 → 下载 URL</option><option value="api">异步图片 API → 轮询下载 URL</option><option value="reference">上传/粘贴参考图</option></Select></Field>
      <Field label="接口类型"><Select disabled={disabled} value={selectedProvider} onChange={selectProvider}><option value="openai">OpenAI 官方</option><option value="compatible">通用兼容 API</option></Select></Field>
      <Field label="视频 API / 文档地址" required><input disabled={disabled} value={config.baseUrl} onChange={(event) => update('baseUrl', event.target.value)} placeholder="可粘贴 API 根地址或供应商文档页"/></Field>
      <Field label="鉴权方式"><Select disabled={disabled} value={config.authMode || 'bearer'} onChange={(value) => update('authMode', value)}><option value="bearer">Authorization: Bearer</option><option value="x-api-key">x-api-key</option><option value="x-goog-api-key">x-goog-api-key</option><option value="query">URL ?key=</option><option value="custom">自定义 Header</option></Select></Field>
      <Field label="视频 API Key" required><input disabled={disabled} type="password" autoComplete="off" value={config.apiKey} onChange={(event) => update('apiKey', event.target.value)} placeholder="仅保存在当前会话"/></Field>
      <Field label="视频请求协议"><Select disabled={disabled} value={config.videoProtocol || 'auto'} onChange={(value) => update('videoProtocol', value)}><option value="auto">自动识别</option><option value="openai">OpenAI multipart /videos</option><option value="media">通用媒体异步任务</option><option value="json">普通兼容 JSON</option></Select></Field>
    </div>
    <div className="pool-note"><Shuffle size={15}/><span><b>媒体模型池</b>：失败时自动切换模型或端点。文本不会发送到媒体模型，避免消耗中转站文本 Tokens。</span></div>
    {config.imageSource !== 'reference' ? <div className="image-api-block"><strong>图片模型（Claude 用户可在此接入 GPT Image）</strong><div className="modal-grid"><Field label="图片 API Base URL"><input disabled={disabled} value={config.imageBaseUrl || ''} onChange={(event) => update('imageBaseUrl', event.target.value)} placeholder="留空则与视频 API 相同"/></Field><Field label="图片 API Key"><input disabled={disabled} type="password" value={config.imageApiKey || ''} onChange={(event) => update('imageApiKey', event.target.value)} placeholder="留空则与视频 Key 相同"/></Field><Field label="图片请求协议"><Select disabled={disabled} value={config.imageProtocol || 'auto'} onChange={(value) => update('imageProtocol', value)}><option value="auto">自动识别</option><option value="openai">OpenAI Images</option><option value="media">通用媒体异步任务</option></Select></Field><PathField label="图片模型池" disabled={disabled} value={config.imageModels || config.imageModel} onChange={(value) => update('imageModels', value)} placeholder="gpt-image-2, gpt-image-1.5"/></div></div> : <p className="reference-mode-note">已启用“只需视频 API”：请在工作台上传商品图或人物参考图，智能体会生成脚本和视频提示词，图片不会发送到图片 API。</p>}
    <VideoSettings config={config} setConfig={setConfig} disabled={disabled}/>
    <button className="advanced-toggle" onClick={() => setAdvanced((value) => !value)}>{advanced ? '收起' : '展开'}高级路由与独立密钥 <ChevronDown size={14}/></button>{advanced ? <div className="advanced-grid"><div className="modal-grid">
      <PathField label="模型检查路径" disabled={disabled} value={config.modelsPath} onChange={(value) => update('modelsPath', value)}/><PathField label="图片生成路径（按行回退）" disabled={disabled} value={config.imagePath} onChange={(value) => update('imagePath', value)}/><PathField label="图片查询路径（{id}）" disabled={disabled} value={config.imageStatusPath} onChange={(value) => update('imageStatusPath', value)}/><PathField label="视频提交路径（按行回退）" disabled={disabled} value={config.videoPath} onChange={(value) => update('videoPath', value)}/><PathField label="视频查询路径（{id}）" disabled={disabled} value={config.videoStatusPath} onChange={(value) => update('videoStatusPath', value)}/><PathField label="视频下载路径（{id}）" disabled={disabled} value={config.videoContentPath} onChange={(value) => update('videoContentPath', value)}/><PathField label="图片 params JSON 覆盖" disabled={disabled} value={config.imageParamsJson || ''} onChange={(value) => update('imageParamsJson', value)} placeholder='例如：{"size":"auto","quality":"high"}'/><PathField label="视频 params JSON 覆盖" disabled={disabled} value={config.videoParamsJson || ''} onChange={(value) => update('videoParamsJson', value)} placeholder='例如：{"duration":"10","aspect_ratio":"9:16"}'/>
      <Field label="视频独立 Base URL"><input disabled={disabled} value={config.videoBaseUrl || ''} onChange={(event) => update('videoBaseUrl', event.target.value)} placeholder="留空则使用主地址"/></Field><Field label="视频独立 API Key"><input disabled={disabled} type="password" value={config.videoApiKey || ''} onChange={(event) => update('videoApiKey', event.target.value)} placeholder="留空则使用主 Key"/></Field>
      <Field label="本地图自动上传地址"><input disabled={disabled} value={config.referenceUploadUrl || ''} onChange={(event) => update('referenceUploadUrl', event.target.value)} placeholder="对象存储、图床或商家上传接口"/></Field><Field label="上传协议"><Select disabled={disabled} value={config.referenceUploadProtocol || 'multipart'} onChange={(value) => update('referenceUploadProtocol', value)}><option value="multipart">multipart 文件上传</option><option value="json">JSON data_url</option><option value="put">原始文件 PUT</option></Select></Field>
      <Field label="文件字段名"><input disabled={disabled} value={config.referenceUploadField || 'file'} onChange={(event) => update('referenceUploadField', event.target.value)} placeholder="file 或 data_url"/></Field><Field label="返回 URL 字段路径"><input disabled={disabled} value={config.referenceUploadResponsePath || ''} onChange={(event) => update('referenceUploadResponsePath', event.target.value)} placeholder="例如 data.url；留空自动识别"/></Field>
      <Field label="上传服务 API Key（可选）"><input disabled={disabled} type="password" value={config.referenceUploadApiKey || ''} onChange={(event) => update('referenceUploadApiKey', event.target.value)} placeholder="留空使用视频 Key"/></Field><Field label="上传鉴权"><Select disabled={disabled} value={config.referenceUploadAuthMode || 'bearer'} onChange={(value) => update('referenceUploadAuthMode', value)}><option value="bearer">Authorization: Bearer</option><option value="x-api-key">x-api-key</option><option value="custom">自定义 Header</option><option value="none">不鉴权</option></Select></Field>
      {config.referenceUploadAuthMode === 'custom' ? <><Field label="上传鉴权 Header"><input disabled={disabled} value={config.referenceUploadAuthHeader || ''} onChange={(event) => update('referenceUploadAuthHeader', event.target.value)} placeholder="例如 X-Token"/></Field><Field label="上传 Key 前缀"><input disabled={disabled} value={config.referenceUploadAuthPrefix || ''} onChange={(event) => update('referenceUploadAuthPrefix', event.target.value)} placeholder="例如 Token（可留空）"/></Field></> : null}
      {config.referenceUploadProtocol === 'put' ? <Field label="PUT 后公网 URL"><input disabled={disabled} value={config.referenceUploadPublicUrl || ''} onChange={(event) => update('referenceUploadPublicUrl', event.target.value)} placeholder="上传完成后可访问的对象 URL"/></Field> : null}
      <Field label="任务回调 URL（可选）"><input disabled={disabled} value={config.notifyUrl || ''} onChange={(event) => update('notifyUrl', event.target.value)} placeholder="https://your-domain.example/webhook"/></Field>{config.authMode === 'custom' ? <><Field label="自定义鉴权 Header"><input disabled={disabled} value={config.authHeader || ''} onChange={(event) => update('authHeader', event.target.value)}/></Field><Field label="自定义鉴权前缀"><input disabled={disabled} value={config.authPrefix || ''} onChange={(event) => update('authPrefix', event.target.value)}/></Field></> : null}{config.authMode === 'query' ? <Field label="URL Key 参数名"><input disabled={disabled} value={config.queryKeyName || 'key'} onChange={(event) => update('queryKeyName', event.target.value)}/></Field> : null}
    </div></div> : null}</div>
    <p className="privacy"><ShieldCheck size={13}/>可直接粘贴 API 根地址或供应商文档地址；测试时会识别公开配置中的 API 入口，不保存文档站品牌或域名。媒体 Key 只进入当前标签页和本机服务内存。</p><div className="modal-actions"><button className="secondary" onClick={loadModels} disabled={loadingModels || disabled}><DatabaseZap size={16}/>{loadingModels ? '读取中…' : '识别并读取模型'}</button><button className="secondary" onClick={testApi} disabled={testing}><Activity size={16}/>{testing ? '识别中…' : '智能识别并测试'}</button><button className="primary" onClick={close}>保存配置</button></div>
  </div></div>
}
